name: Deploy

on:
  push:
    tags:
      - v*
    branches: [main, experimental]
    paths-ignore: ['**.md']
  workflow_dispatch:

env:
  DOCKER_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8 #linux/s390x,linux/ppc64le

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # - name: Install dependencies
      #   run: npm i

      # - name: Test
      #   run: npm run lint -- --max-warnings=0

      - name: Extract version
        id: version
        run: |
          set -x
          version=$(node -e "
            const pkgVersion = require('./package.json').version;
            const ref = process.env.GITHUB_REF.split('refs/heads/');

            console.log(pkgVersion, ref);
            // process.exit(1);
            // console.log(!.includes('dev') &&  ? 'dev' : 'latest')
          ")
          echo ::set-output name=version::${version}
      
      # - name: Publish to npm
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     tag: 

      # - name: Change scope
      #   env:
      #     INPUT_TOKEN: ""
      #   run: npm init --scope=luwol03 -y

      # - name: Publish to gpr
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     registry: https://npm.pkg.github.com/
