name: Deploy

on:
  push:
    branches: [main, experimental]

env:
  DOCKER_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8 #linux/s390x,linux/ppc64le

jobs:
  build: 
    name: 🔧 build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # - name: Install dependencies
      #   run: npm i

      # - name: Test
      #   run: npm run lint -- --max-warnings=0

      - name: Extract version
        id: version
        run: |
          mv package.json package.json.bak
          npm i --no-save --no-package-look @actions/core
          mv package.json.bak package.json
          set -x
          node -e "
            const core = require('@actions/core')
            const { version } = require('./package.json');
            const branch = process.env.GITHUB_REF.split('refs/heads/')[1];

            const tag = version.includes('experimental') && branch === 'experimental' ? 'experimental'
              : !version.includes('experimental') && branch === 'main' ? 'latest' : null;

            if (!tag) {
              core.setFailed('you may forgot to remove the experimental label');
              process.exit(1);
            }

            core.setOutput('version', version);
            core.setOutput('tag', tag);
          "
          echo "::set-output name=test::world"

  npm:
    name: 📦 npm
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          set -x
          echo ${{needs.build.steps.version.outputs.version}}
          echo ${{needs.build.steps.version.outputs.tag}}
          echo ${{toJSON(needs)}}
      # - name: Publish to npm
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     tag: 

      # - name: Change scope
      #   env:
      #     INPUT_TOKEN: ""
      #   run: npm init --scope=luwol03 -y

      # - name: Publish to gpr
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     registry: https://npm.pkg.github.com/
